import { NavigationHeader } from '@/modules/components/navigation-header/NavigationHeader';
import { Presentation } from '@/modules/components/presentation/Presentation';
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Nos casamos!</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1"/>
                <link rel="icon"
                      href="/favicon.ico"/>
                <link rel="preconnect"
                      href="https://fonts.googleapis.com"/>
                <link rel="preconnect"
                      href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Jost:ital,wght@0,400;0,700;1,400;1,700&display=swap"
                      rel="stylesheet"/>
            </Head>
            <main className="flex flex-col font-sans">
                <NavigationHeader/>
                <Presentation/>
            </main>
        </>
    )
}
