import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Nos casamos!</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1"/>
                <link rel="icon"
                      href="/favicon.ico"/>
            </Head>
            <main className="flex flex-col items-center justify-center min-h-screen py-2">
                <h1 className="text-3xl font-bold underline">
                    Lore y Rober, Nos Casamos!
                </h1>
                <p className="text-xl">Esto es simplemente una prueba para comprobar que github pages funciona</p>
            </main>
        </>
    )
}
